-- ============================================================================
-- Berry Books Database - DDL Script
-- ============================================================================
-- Purpose: Create all tables with constraints and indexes
-- Database: HSQLDB 2.7.x
-- Encoding: UTF-8
-- ============================================================================

-- ============================================================================
-- Master Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PUBLISHER Table (出版社マスタ)
-- ----------------------------------------------------------------------------
CREATE TABLE PUBLISHER (
    PUBLISHER_ID    INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PUBLISHER_NAME  VARCHAR(30)     NOT NULL
);

-- ----------------------------------------------------------------------------
-- CATEGORY Table (カテゴリマスタ)
-- ----------------------------------------------------------------------------
CREATE TABLE CATEGORY (
    CATEGORY_ID     INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME   VARCHAR(20)     NOT NULL
);

-- ============================================================================
-- Book and Stock Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- BOOK Table (書籍)
-- ----------------------------------------------------------------------------
CREATE TABLE BOOK (
    BOOK_ID         INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOOK_NAME       VARCHAR(80)     NOT NULL,
    AUTHOR          VARCHAR(40)     NOT NULL,
    CATEGORY_ID     INTEGER         NOT NULL,
    PUBLISHER_ID    INTEGER         NOT NULL,
    PRICE           INTEGER         NOT NULL,
    CONSTRAINT FK_BOOK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID)
);

-- Create indexes for search optimization
CREATE INDEX IDX_BOOK_CATEGORY ON BOOK(CATEGORY_ID);
CREATE INDEX IDX_BOOK_NAME ON BOOK(BOOK_NAME);

-- ----------------------------------------------------------------------------
-- STOCK Table (在庫) - with Optimistic Locking
-- ----------------------------------------------------------------------------
CREATE TABLE STOCK (
    BOOK_ID         INTEGER         PRIMARY KEY,
    QUANTITY        INTEGER         NOT NULL,
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT FK_STOCK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

-- ============================================================================
-- Customer Table
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CUSTOMER Table (顧客)
-- ----------------------------------------------------------------------------
CREATE TABLE CUSTOMER (
    CUSTOMER_ID     INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR(30)     NOT NULL,
    EMAIL           VARCHAR(30)     NOT NULL UNIQUE,
    PASSWORD        VARCHAR(60)     NOT NULL,
    BIRTHDAY        DATE,
    ADDRESS         VARCHAR(120)
);

-- Create unique index for login optimization
CREATE UNIQUE INDEX IDX_CUSTOMER_EMAIL ON CUSTOMER(EMAIL);

-- ============================================================================
-- Order Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ORDER_TRAN Table (注文取引)
-- ----------------------------------------------------------------------------
CREATE TABLE ORDER_TRAN (
    ORDER_TRAN_ID       INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_DATE          DATE            NOT NULL,
    CUSTOMER_ID         INTEGER         NOT NULL,
    TOTAL_PRICE         INTEGER         NOT NULL,
    DELIVERY_PRICE      INTEGER         NOT NULL,
    DELIVERY_ADDRESS    VARCHAR(30)     NOT NULL,
    SETTLEMENT_TYPE     INTEGER         NOT NULL,
    CONSTRAINT FK_ORDER_TRAN_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- Create indexes for order history queries
CREATE INDEX IDX_ORDER_TRAN_CUSTOMER ON ORDER_TRAN(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_TRAN_DATE ON ORDER_TRAN(ORDER_DATE);

-- ----------------------------------------------------------------------------
-- ORDER_DETAIL Table (注文明細) - Composite Primary Key
-- ----------------------------------------------------------------------------
CREATE TABLE ORDER_DETAIL (
    ORDER_TRAN_ID       INTEGER         NOT NULL,
    ORDER_DETAIL_ID     INTEGER         NOT NULL,
    BOOK_ID             INTEGER         NOT NULL,
    PRICE               INTEGER         NOT NULL,
    COUNT               INTEGER         NOT NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (ORDER_TRAN_ID, ORDER_DETAIL_ID),
    CONSTRAINT FK_ORDER_DETAIL_TRAN FOREIGN KEY (ORDER_TRAN_ID) REFERENCES ORDER_TRAN(ORDER_TRAN_ID),
    CONSTRAINT FK_ORDER_DETAIL_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

-- Create index for book sales analysis
CREATE INDEX IDX_ORDER_DETAIL_BOOK ON ORDER_DETAIL(BOOK_ID);

-- ============================================================================
-- End of DDL Script
-- ============================================================================
